//------------------------------------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(43CAC48C-9F2A-4FDE-B829-E63CABB80E73),
    pointer_default(unique),
	// !!!!! Pri COM INTERFACE, ktory je ma byt MARSHALED NESMIE byt nastaveny ATTRIBUTE [local] a zaroven (uplne NELOGICKY) NESMIE byt definovany v SCOPE 'library', ale MIMO NEHO.
	// !!!!! Aj ked je NASTAVENY [oleautomation], tak PS DLL MUSI BYT ZAREGISTROVANA.
	//oleautomation
]
interface IFreeThreadingModelTest : IUnknown
{
	HRESULT IncrementValue(void);
	HRESULT GetValue([out] long* Value);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
	uuid(05B8ADAD-1726-4CA5-9047-7C327C9B7B0E),
	version(1.0),
]
library FreeThreadingModelServerLib
{
	importlib("stdole2.tlb");

    [
        uuid(D348A05D-3A32-42F8-B41F-0A31B495F3BC),
    ]
	coclass FreeThreadingModelObject
	{
		[default] interface IFreeThreadingModelTest;
	};
};
//------------------------------------------------------------------------------------------------------