//------------------------------------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(1F838F40-5FF3-42FF-9807-25E9811D01C9),
    pointer_default(unique),
	// !!!!! Pri COM INTERFACE, ktory je ma byt MARSHALED NESMIE byt nastaveny ATTRIBUTE [local].
]
interface IExternalConnectionTest : IUnknown
{
	HRESULT IncrementValue(void);
	HRESULT GetValue([out] long* Value);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
	uuid(B4F0C2A7-9521-476C-AFFD-BA70655610EF),
	version(1.0),
]
library ExternalConnectionServerLib
{
	importlib("stdole2.tlb");

    [
        uuid(413F464E-2222-4752-83A7-B5526A7C64DA),
    ]
	coclass ExternalConnectionObject
	{
		[default] interface IExternalConnectionTest;
	};
};
//------------------------------------------------------------------------------------------------------