<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>my.example</groupId>
	<artifactId>IntroductionToMaven</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<properties>
		<java.version>25</java.version>

		<maven.compiler.source>25</maven.compiler.source>
		<maven.compiler.target>25</maven.compiler.target>

		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<!-- V MAVEN sa DEPENDENCIES urcuju v ELEMENT [project->dependencies]. -->
	<dependencies>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
			<version>6.0.3</version>
			<scope>test</scope>
		</dependency>

		<!-- !!! MAVEN PLUGIN SUREFIRE realizuje spustatnie UNITS TESTS a INTEGRATION TESTS. -->
		<dependency>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-surefire-plugin</artifactId>
			<version>3.5.5</version>
			<scope>compile</scope>
		</dependency>

		<!-- !!! MAVEN PLUGIN DEPENDENCY realizuje ANALYZE daneho PROJECT. -->
		<dependency>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-dependency-plugin</artifactId>
			<version>3.10.0</version>
			<scope>compile</scope>
		</dependency>

		<!-- !!! MAVEN PLUGIN SITE realizuje ANALYZE daneho PROJECT. -->
		<dependency>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-site-plugin</artifactId>
			<version>3.21.0</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<!-- !!! MAVEN PLUGIN SUREFIRE realizuje spustatnie UNITS TESTS a INTEGRATION TESTS. -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.5.5</version>
			</plugin>

			<!-- !!! MAVEN PLUGIN DEPENDENCY realizuje ANALYZE daneho PROJECT. -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>3.10.0</version>
				<configuration>
					<ignoreNonCompile>true</ignoreNonCompile>
				</configuration>
			</plugin>

			<!-- !!! MAVEN PLUGIN SITE realizuje ANALYZE daneho PROJECT. -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-site-plugin</artifactId>
				<version>3.21.0</version>
			</plugin>
		</plugins>
	</build>
</project>