# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  containerRegistry: 'mybookcontainer.azurecr.io'
  imageRepository: 'myazureprogram'
  tag: 'latest'

steps:
# !!!!! TASK pripravi SETTINGS.
- task: AzureAppServiceSettings@1
  displayName: Update settings
  inputs:
    # !!!!! AZURE SUBSCRIPTION sa ziskava pomocou COMMAND [az account subscription list].
    # !!!!! AZURE SUBSCRIPTION SERVICE CONNECTION sa vytvara pomocou COMMAND [az devops service-endpoint create --project MyAzureProgramProject --organization https://dev.azure.com/timmyanderson1976/ --service-endpoint-configuration "MyEndpointConfigurationResourceManager.json"].
    # !!!!! FILE [MyEndpointConfigurationResourceManager.json] musi obsahovat konfiguraciu SERVICE CONNECTION.
    # !!!!! Po vytvoreni SERVICE CONNECTION je potrebne spustit COMMAND [az devops service-endpoint update --id "8dfae7b3-bdaa-4066-882e-23c40e786ef8" --project MyAzureProgramProject --organization https://dev.azure.com/timmyanderson1976/ --enable-for-all true], aby sa SERVICE CONNECTION bola pristupna pre vsetky PIPELINES.
    azureSubscription: 'MyResourceManagerManuallyCreated'
    appName: 'MyAzureProgram'
    resourceGroupName: 'MyBook'
    # !!!!! USER NAME pre VALUE [DOCKER_REGISTRY_SERVER_USERNAME] sa ziskava pomocou COMMAND [az acr credential show].
    # !!!!! PASSWORD VALUE [DOCKER_REGISTRY_SERVER_PASSWORD] sa cita z vytvorenej VARIABLE.
    # !!!!! PASSWORD sa ziskava pomocou COMMAND [az acr credential show].
    appSettings: |
      [
        {
          "name": "DOCKER_REGISTRY_SERVER_URL",
          "value": "$(containerRegistry)",
          "slotSetting": false
        },
        {
          "name": "DOCKER_REGISTRY_SERVER_USERNAME",
          "value": "mybookcontainer",
          "slotSetting": false
        },
        {
          "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
          "value": "$(MyPassword)",
          "slotSetting": false
        }
      ]
- task: AzureWebAppContainer@1
  inputs:
    # !!!!! AZURE SUBSCRIPTION sa ziskava pomocou COMMAND [az account subscription list].
    # !!!!! AZURE SUBSCRIPTION SERVICE CONNECTION sa vytvara pomocou COMMAND [az devops service-endpoint create --project MyAzureProgramProject --organization https://dev.azure.com/timmyanderson1976/ --service-endpoint-configuration "MyEndpointConfigurationResourceManager.json"].
    # !!!!! FILE [MyEndpointConfigurationResourceManager.json] musi obsahovat konfiguraciu SERVICE CONNECTION.
    # !!!!! Po vytvoreni SERVICE CONNECTION je potrebne spustit COMMAND [az devops service-endpoint update --id "8dfae7b3-bdaa-4066-882e-23c40e786ef8" --project MyAzureProgramProject --organization https://dev.azure.com/timmyanderson1976/ --enable-for-all true], aby sa SERVICE CONNECTION bola pristupna pre vsetky PIPELINES.
    azureSubscription: 'MyResourceManagerManuallyCreated'
    appName: 'MyAzureProgram'
    containers: '$(containerRegistry)/$(imageRepository):$(tag)'
    containerCommand: 'dotnet MyAzureProgram.dll'