//------------------------------------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(21F82740-3C47-41B0-AF6B-6F243D3AC79F),
    pointer_default(unique),
	// !!! COM INTERFACE NESMIE BYT [local], lebo sa ma preniest cez HRANICE PROCESSES (APARTMENTS).
]
interface IName : IUnknown
{
	// !!!!! METHODS musia mat PARAMTERS prisposobene tak, aby bol mozny MARSHALLING. Napriklad pri ARRAYS to znaci pouzitie ATTRIBUTE [size_is()].
	HRESULT SetFirstName([in,string] wchar_t* FirstName);
	HRESULT SetLastName([in,string] wchar_t* LastName);
	HRESULT SetAge([in] int Age);
	HRESULT GetFirstName([in] int BufferSize, [out,retval,size_is(BufferSize)] wchar_t* FirstName);
	HRESULT GetLastName([in] int BufferSize, [out,retval,size_is(BufferSize)] wchar_t* LastName);
	HRESULT GetAge([out,retval] int* Age);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
	uuid(9D36D3F9-7153-4B9D-B6D7-0A6FB4042480),
	version(1.0),
]
library OutOfProcessWithMarshallingServerLib
{
	importlib("stdole2.tlb");

    [
        uuid(1C856AB3-520C-4B2A-B6AC-4A12FEBC06B3),
    ]
	coclass OutOfProcessWithMarshallingObject
	{
		[default] interface IName;
	};
};
//------------------------------------------------------------------------------------------------------