//------------------------------------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(D83BC28B-DDBD-4316-8087-AF0E11E401CA),
    pointer_default(unique),
	// !!!!! Pri COM INTERFACE, ktory je ma byt MARSHALED NESMIE byt nastaveny ATTRIBUTE [local] a zaroven (uplne NELOGICKY) NESMIE byt definovany v SCOPE 'library', ale MIMO NEHO.
]
interface IFTMTest : IUnknown
{
	HRESULT IncrementValue(void);
	HRESULT GetValue([out] long* Value);
	HRESULT IncrementValueToRemoteObject(void);
	HRESULT GetValueFromRemoteObject([out] long* Value);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
	uuid(474E334E-F1D5-40C9-A9B2-7F00F2A977B0),
	version(1.0),
]
library FTMServerLib
{
	importlib("stdole2.tlb");

    [
        uuid(C0F5A9A6-6621-4CF1-AB5A-08508FE46911),
    ]
	coclass FTMObject
	{
		[default] interface IFTMTest;
	};
};
//------------------------------------------------------------------------------------------------------