//------------------------------------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(84B88743-D0EE-438A-929F-4C8CE49137F3),
    pointer_default(unique),
    local,
	oleautomation
]
interface IMyFileMonikerName : IUnknown
{
	HRESULT SetFirstName([in,string] BSTR FirstName);
	HRESULT SetLastName([in,string] BSTR LastName);
	HRESULT SetAge([in] int Age);
	HRESULT GetFirstName([in] int BufferSize, [out,string,retval] BSTR* FirstName);
	HRESULT GetLastName([in] int BufferSize, [out,string,retval] BSTR* LastName);
	HRESULT GetAge([out,retval] int* Age);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
	uuid(8D340BEA-29D1-4A81-8FB4-246D391132D9),
	version(1.0),
]
library MyFileMonikerServerLib
{
	importlib("stdole2.tlb");

    [
        uuid(B9A83743-624A-46AD-B409-DA0816C9F1C5),
    ]
	coclass MyFileMonikerObject
	{
		[default] interface IMyFileMonikerName;
	};
};
//------------------------------------------------------------------------------------------------------