//--------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//--------------------------------------------------------------------------------------------------------
namespace CompositeDCAutomaticClient.CCompositeDCProxy
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.datacontract.org/2004/07/CompositeDCLibrary")]
    [System.SerializableAttribute()]
    public partial class CFriend : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CompositeDCAutomaticClient.CCompositeDCProxy.CName[] FriendsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CompositeDCAutomaticClient.CCompositeDCProxy.CName MyNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CompositeDCAutomaticClient.CCompositeDCProxy.CName[] Friends
        {
            get
            {
                return this.FriendsField;
            }
            set
            {
                this.FriendsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CompositeDCAutomaticClient.CCompositeDCProxy.CName MyName
        {
            get
            {
                return this.MyNameField;
            }
            set
            {
                this.MyNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.datacontract.org/2004/07/CompositeDCLibrary")]
    [System.SerializableAttribute()]
    public partial class CName : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompositeDCAutomaticClient.CCompositeDCProxy.ICompositeDCContract")]
    public interface ICompositeDCContract
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompositeDCContract/GetFriend", ReplyAction="http://tempuri.org/ICompositeDCContract/GetFriendResponse")]
        CompositeDCAutomaticClient.CCompositeDCProxy.CFriend GetFriend();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompositeDCContract/SendFriend", ReplyAction="http://tempuri.org/ICompositeDCContract/SendFriendResponse")]
        void SendFriend(CompositeDCAutomaticClient.CCompositeDCProxy.CFriend Friend);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ICompositeDCContractChannel : CompositeDCAutomaticClient.CCompositeDCProxy.ICompositeDCContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CompositeDCContractClient : System.ServiceModel.ClientBase<CompositeDCAutomaticClient.CCompositeDCProxy.ICompositeDCContract>, CompositeDCAutomaticClient.CCompositeDCProxy.ICompositeDCContract
    {
        
        public CompositeDCContractClient()
        {
        }
        
        public CompositeDCContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public CompositeDCContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CompositeDCContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CompositeDCContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public CompositeDCAutomaticClient.CCompositeDCProxy.CFriend GetFriend()
        {
            return base.Channel.GetFriend();
        }
        
        public void SendFriend(CompositeDCAutomaticClient.CCompositeDCProxy.CFriend Friend)
        {
            base.Channel.SendFriend(Friend);
        }
    }
}
//--------------------------------------------------------------------------------------------------------