//------------------------------------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(D179F4FA-DCAE-456F-B186-2AF54A0D468F),
    pointer_default(unique),
	// !!!!! Pri COM INTERFACE, ktory je ma byt MARSHALED NESMIE byt nastaveny ATTRIBUTE [local] a zaroven (uplne NELOGICKY) NESMIE byt definovany v SCOPE 'library', ale MIMO NEHO.
]
interface IMyConnectionPointsCallback : IUnknown
{
	HRESULT SendMessageToClient([in] BSTR Message);
};
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(574AC1CE-A230-4D8A-8932-07565A03AE1F),
    pointer_default(unique),
	// !!!!! Pri COM INTERFACE, ktory je ma byt MARSHALED NESMIE byt nastaveny ATTRIBUTE [local] a zaroven (uplne NELOGICKY) NESMIE byt definovany v SCOPE 'library', ale MIMO NEHO.
]
interface IMyConnectionPoints : IUnknown
{
	HRESULT SendMessageToServer([in] BSTR Message);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
	uuid(94749E9A-F72F-4A57-877A-7BA7567E73B9),
	version(1.0),
]
library ConnectionPointsServerLib
{
	importlib("stdole2.tlb");

    [
        uuid(013B83E1-964F-4970-8F99-96FE1466C78B),
    ]
	coclass ConnectionPointsObject
	{
		[default] interface IMyConnectionPoints;
		// !!! ATTRIBUTE [source] sa definuje OUTGOING COM INTERFACE.
		[source] interface IMyConnectionPointsCallback;
	};
};
//------------------------------------------------------------------------------------------------------