//--------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//--------------------------------------------------------------------------------------------------------

namespace HelloWCFAutoClient.CHelloWCFProxy
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelloWCFAutoClient.CHelloWCFProxy.IHelloWCFContract")]
    public interface IHelloWCFContract
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloWCFContract/Say", ReplyAction="http://tempuri.org/IHelloWCFContract/SayResponse")]
        void Say(string Input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IHelloWCFContractChannel : HelloWCFAutoClient.CHelloWCFProxy.IHelloWCFContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class HelloWCFContractClient : System.ServiceModel.ClientBase<HelloWCFAutoClient.CHelloWCFProxy.IHelloWCFContract>, HelloWCFAutoClient.CHelloWCFProxy.IHelloWCFContract
    {
        
        public HelloWCFContractClient()
        {
        }
        
        public HelloWCFContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public HelloWCFContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public HelloWCFContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public HelloWCFContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void Say(string Input)
        {
            base.Channel.Say(Input);
        }
    }
}
//--------------------------------------------------------------------------------------------------------