//------------------------------------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(1E353167-DFFC-4374-92A6-504259BE17D9),
    pointer_default(unique),
]
interface IStandardMarshalingTest : IUnknown
{
	HRESULT IncrementValue(void);
	HRESULT GetValue([out] long* Value);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
	uuid(6078AA07-FCCE-4101-AD46-63DD56312C75),
	version(1.0),
]
library StandardMarshalingServerLib
{
	importlib("stdole2.tlb");

    [
        uuid(A7D6E752-4695-4958-BF57-BCE759EB3C97),
    ]
	coclass StandardMarshalingObject
	{
		[default] interface IStandardMarshalingTest;
	};
};
//------------------------------------------------------------------------------------------------------