//------------------------------------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(0B2BAE96-B537-4B45-AD84-A044E31F934C),
    pointer_default(unique),
    local
]
interface IInnerAggregationText : IUnknown
{
	HRESULT SetText([in,string] wchar_t* Text);
	// ALTERNATIVNE sa da pouzit aj [HRESULT GetText([in] int BufferSize, [out,retval,size_is(BufferSize)] wchar_t* Text)].
	HRESULT GetText([in] int BufferSize, [out,string,retval] wchar_t** Text);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
	uuid(A35D5270-4C17-478E-AF8E-F9EB16E7D7BA),
	version(1.0),
]
library InnerAggregationServerLib
{
	importlib("stdole2.tlb");

    [
        uuid(F5ED13D1-CF4A-41CC-96D7-9F54E995052F),
    ]
	coclass InnerAggregationObject
	{
		[default] interface IInnerAggregationText;
	};
};
//------------------------------------------------------------------------------------------------------