//------------------------------------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(DEDF2F66-3D4D-497C-B9D4-E86613EE5E9F),
    pointer_default(unique),
    local
]
interface IGetText1 : IUnknown
{
	// ALTERNATIVNE sa da pouzit aj [HRESULT GetText([in] int BufferSize, [out,retval,size_is(BufferSize)] wchar_t* Text)].
	HRESULT GetText1([in] int BufferSize, [out,string,retval] wchar_t** Text);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(280BA5E9-9EF5-4E68-9E58-BB0BE441F208),
    pointer_default(unique),
    local
]
interface IGetText2 : IUnknown
{
	// ALTERNATIVNE sa da pouzit aj [HRESULT GetText([in] int BufferSize, [out,retval,size_is(BufferSize)] wchar_t* Text)].
	HRESULT GetText2([in] int BufferSize, [out,string,retval] wchar_t** Text);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(8A50080A-CF08-44A8-8C57-B4C73843D387),
    pointer_default(unique),
    local
]
interface IGetText3 : IUnknown
{
	HRESULT GetText3([in] int BufferSize, [out,string,retval] wchar_t** Text);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
	uuid(B23C4ED4-AB93-417E-A72F-D8978688A5F2),
	version(1.0),
]
library QITestServerLib
{
	importlib("stdole2.tlb");

    [
        uuid(DCAE9847-CCA3-4B1F-8E80-9E6C0484F9A4),
    ]
	coclass QITestObject
	{
		[default] interface IGetText1;
		interface IGetText2;
		interface IGetText3;
	};
};
//------------------------------------------------------------------------------------------------------