//------------------------------------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(F68296BA-8181-4D93-9C94-7F530CD0EFF8),
    pointer_default(unique),
	// !!!!! Pri COM INTERFACE, ktory je ma byt MARSHALED NESMIE byt nastaveny ATTRIBUTE [local].
	// !!!!! Aj ked je NASTAVENY [oleautomation], tak PS DLL MUSI BYT ZAREGISTROVANA.
	//oleautomation
]
interface IApartmentThreadingModelTest : IUnknown
{
	HRESULT IncrementValue(void);
	HRESULT GetValue([out] long* Value);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
	uuid(371F95C5-779A-406C-92AB-13FD805180E7),
	version(1.0),
]
library ApartmentThreadingModelServerLib
{
	importlib("stdole2.tlb");

    [
        uuid(6FCC169E-4F6F-4000-A5B6-190B6E18FCE2),
    ]
	coclass ApartmentThreadingModelObject
	{
		[default] interface IApartmentThreadingModelTest;
	};
};
//------------------------------------------------------------------------------------------------------