spring:
  application:
    name: IntroductionToSpringBoot
  main:
    banner-mode: off

logging:
  level:
    my:
      example:
        # !!! LOG CONFIGURATIO aplikovana na NAMESPACE.
        IntroductionToSpringBoot: DEBUG

        # !!! LOG CONFIGURATIO aplikovana na CLASS.
        IntroductionToSpringBoot.CMain2Controller: WARN