//------------------------------------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(4FD8CBC3-914C-4B34-BC82-615C73FC8F31),
    pointer_default(unique),
	// !!!!! Pri COM INTERFACE, ktory je ma byt MARSHALED NESMIE byt nastaveny ATTRIBUTE [local] a zaroven (uplne NELOGICKY) NESMIE byt definovany v SCOPE 'library', ale MIMO NEHO.
]
interface IObjectUsedByFTMTest : IUnknown
{
	HRESULT IncrementValue(void);
	HRESULT GetValue([out] long* Value);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
	uuid(083A6D11-08BE-427B-9CB1-24077002FCBE),
	version(1.0),
]
library ObjectUsedByFTMServerLib
{
	importlib("stdole2.tlb");

    [
        uuid(65D8909C-D4A0-47EF-A584-0DA233C724D5),
    ]
	coclass ObjectUsedByFTMObject
	{
		[default] interface IObjectUsedByFTMTest;
	};
};
//------------------------------------------------------------------------------------------------------