apiVersion: apps/v1

kind: Deployment

metadata:
  name: my-program

spec:
  replicas: 1

  selector:
    matchLabels:
      app: my-program

  template:
    metadata:
      labels:
        app: my-program

    spec:
      nodeSelector:
        "kubernetes.io/os": linux

      containers:
      - name: my-program
        image: docker.io/timmyanderson/kubernetesandcontainers:1.0.0

        ports:
        - containerPort: 8080
          name: my-program

        resources:
          requests:
            cpu: 1m
            memory: 200Mi

          limits:
            cpu: 1000m
            memory: 512Mi



---


apiVersion: v1

kind: Service

metadata:
  name: my-program

spec:
  ports:
  - port: 80
    targetPort: 8080

  selector:
    app: my-program

  type: LoadBalancer