//------------------------------------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
//------------------------------------------------------------------------------------------------------
[
	object,
	uuid(69086C22-221F-4A29-9F91-2D6EB9D1EFFC),
	pointer_default(unique),
	// !!!!! Pri COM INTERFACE, ktory je ma byt MARSHALED NESMIE byt nastaveny ATTRIBUTE [local] a zaroven (uplne NELOGICKY) NESMIE byt definovany v SCOPE 'library', ale MIMO NEHO.
]
interface IUnmanagedCOMServerCallback : IUnknown
{
//------------------------------------------------------------------------------------------------------
	HRESULT SendMessageToClient([in] BSTR Message);
//------------------------------------------------------------------------------------------------------
};
//------------------------------------------------------------------------------------------------------
[
	object,
	uuid(DB83FED1-ED27-425C-87B7-FF5036C1F08F),
	pointer_default(unique),
	// !!!!! Pri COM INTERFACE, ktory je ma byt MARSHALED NESMIE byt nastaveny ATTRIBUTE [local] a zaroven (uplne NELOGICKY) NESMIE byt definovany v SCOPE 'library', ale MIMO NEHO.
]
interface IUnmanagedCOMServer : IUnknown
{
//------------------------------------------------------------------------------------------------------
	HRESULT RegisterCallback([in] IUnmanagedCOMServerCallback* Callback);
	HRESULT UnRegisterCallback(void);
	HRESULT SendMessageToServer([in] BSTR Message);
	HRESULT PrintMessage([in] BSTR Message);
	HRESULT LoadName([out] BSTR* Name, [out] int* Age);
	HRESULT SaveName([in] BSTR Name, [in] int Age);
	HRESULT ArrayTest1([in] int ArraySize, [in,out,size_is(ArraySize)] int* Array);
	HRESULT ArrayTest2([in,out] SAFEARRAY(int)* Array);
//------------------------------------------------------------------------------------------------------
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
	uuid(493FFE87-B267-4D96-8CF5-0D786FAA604A),
	version(1.0),
]
library UnmanagedCOMServerLib
{
//------------------------------------------------------------------------------------------------------
	importlib("stdole2.tlb");

	[
		uuid(91C07319-AD70-4A12-A070-DC8E76A5BC94),
	]
	coclass UnmanagedCOMObject
	{
		[default] interface IUnmanagedCOMServer;
		interface IUnmanagedCOMServerCallback;
	};
//------------------------------------------------------------------------------------------------------
};
//------------------------------------------------------------------------------------------------------