//------------------------------------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(65A09033-94A6-47A4-8C8F-5BA1FE41DFC9),
    pointer_default(unique),
	// !!! COM INTERFACE NESMIE BYT [local], lebo sa ma preniest cez HRANICE PROCESSES (APARTMENTS).
]
interface IName : IUnknown
{
	// !!!!! METHODS musia mat PARAMTERS prisposobene tak, aby bol mozny MARSHALLING. Napriklad pri ARRAYS to znaci pouzitie ATTRIBUTE [size_is()].
	HRESULT SetName([in,string] wchar_t* Name);
	HRESULT GetName([in] int BufferSize, [out,retval,size_is(BufferSize)] wchar_t* Name);
	HRESULT PrintSecuritySettings(void);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
	uuid(8F1CC7D8-89E6-470D-A7E6-BD53ADDD0014),
	version(1.0),
]
library COMSecurityServerLib
{
	importlib("stdole2.tlb");

    [
        uuid(9D19A76B-4368-4818-89D1-F9E27E0B96A6),
    ]
	coclass COMSecurityObject
	{
		[default] interface IName;
	};
};
//------------------------------------------------------------------------------------------------------