//------------------------------------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(646D0B35-9E94-439A-B049-4C59120940B5),
    pointer_default(unique),
    local
]
interface IGetText1 : IUnknown
{
	// ALTERNATIVNE sa da pouzit aj [HRESULT GetText([in] int BufferSize, [out,retval,size_is(BufferSize)] wchar_t* Text)].
	// METHOD je ROVNAKO POMENOVANA ako v IGetText2.
	HRESULT GetText([in] int BufferSize, [out,string,retval] wchar_t** Text);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(06C84E8D-52D5-4080-BFC7-7D8C933AD616),
    pointer_default(unique),
    local
]
interface IGetText2 : IUnknown
{
	// METHOD je ROVNAKO POMENOVANA ako v IGetText1.
	// ALTERNATIVNE sa da pouzit aj [HRESULT GetText([in] int BufferSize, [out,retval,size_is(BufferSize)] wchar_t* Text)].
	HRESULT GetText([in] int BufferSize, [out,string,retval] wchar_t** Text);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
	uuid(B299B7F1-9811-4300-B3B1-AC587A712444),
	version(1.0),
]
library CompositionServerLib
{
	importlib("stdole2.tlb");

    [
        uuid(48C0A70D-E917-49D9-855A-DC4459066B1C),
    ]
	coclass CompositionObject
	{
		[default] interface IGetText1;
		interface IGetText2;
	};
};
//------------------------------------------------------------------------------------------------------