//------------------------------------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(7B494096-E8B0-46B2-AC87-9A0C1B04395F),
    pointer_default(unique),
    local
]
interface IInProcessName : IUnknown
{
	HRESULT SetFirstName([in,string] wchar_t* FirstName);
	HRESULT SetLastName([in,string] wchar_t* LastName);
	HRESULT SetAge([in] int Age);
	// ALTERNATIVNE sa da pouzit aj [HRESULT GetFirstName([in] int BufferSize, [out,retval,size_is(BufferSize)] wchar_t* FirstName)].
	HRESULT GetFirstName([in] int BufferSize, [out,string,retval] wchar_t** FirstName);
	// ALTERNATIVNE sa da pouzit aj [HRESULT GetLastName([in] int BufferSize, [out,retval,size_is(BufferSize)] wchar_t* LastName)].
	HRESULT GetLastName([in] int BufferSize, [out,string,retval] wchar_t** LastName);
	HRESULT GetAge([out,retval] int* Age);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
	uuid(8EE13DBC-0F00-4BB2-BA58-4EEF15743803),
	version(1.0),
]
library InProcessServerLib
{
	importlib("stdole2.tlb");

    [
        uuid(4E72CC54-3EC7-4240-9AAB-45285DB4B2FD),
    ]
	coclass InProcessObject
	{
		[default] interface IInProcessName;
	};
};
//------------------------------------------------------------------------------------------------------