//------------------------------------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(5C0AE81B-2AA7-43E6-9CC4-3CA45991E38C),
    pointer_default(unique),
    local
]
interface IOuterAggregationText : IUnknown
{
	HRESULT SetText([in,string] wchar_t* Text);
	// ALTERNATIVNE sa da pouzit aj [HRESULT GetText([in] int BufferSize, [out,retval,size_is(BufferSize)] wchar_t* Text)].
	HRESULT GetText([in] int BufferSize, [out,string,retval] wchar_t** Text);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
	uuid(7325B17E-5E10-4F78-A8DE-231AEA6CEDA7),
	version(1.0),
]
library OuterAggregationServerLib
{
	importlib("stdole2.tlb");

    [
        uuid(DC12616F-3D71-46E2-A6E7-03E736FE20DF),
    ]
	coclass OuterAggregationObject
	{
		[default] interface IOuterAggregationText;
	};
};
//------------------------------------------------------------------------------------------------------