//------------------------------------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(D58B5FD6-D7A7-4373-824F-DBBA096B0CF4),
    pointer_default(unique),
	// !!!!! Pri COM INTERFACE, ktory je ma byt MARSHALED NESMIE byt nastaveny ATTRIBUTE [local].
]
interface ICustomMarshalingByReferenceTest : IUnknown
{
	HRESULT IncrementValue(void);
	HRESULT GetValue([out] long* Value);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
	uuid(F4D6B5FA-93A1-43C0-AE29-C47FA4172400),
	version(1.0),
]
library CustomMarshalingByReferenceServerLib
{
	importlib("stdole2.tlb");

    [
        uuid(42F8F1E5-C641-4FB6-A4BA-3593B248856C),
    ]
	coclass CustomMarshalingByReferenceObject
	{
		[default] interface ICustomMarshalingByReferenceTest;
	};
};
//------------------------------------------------------------------------------------------------------