# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

# !!!!! FILE predstavuje BUILD PIPELINE, ktora vykona BUILD daneho PROJECT a spustenie TESTS.

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # !!!!! Nastavi sa ENVIRONMENT na .NET 8.0..
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # !!!!! Moj CUSTOM STEP na zobrazenie obsahu WORKING DIRECTORY.
    - name: DIR
      run: ls

    # !!!!! Stiahnu sa DEPENDENCIES pre .NET 8.0..
    - name: Restore dependencies
      run: dotnet restore

    # !!!!! Vykona sa BUILD PROGRAMU.
    - name: Build
      run: dotnet build --no-restore

    # !!!!! Spustia sa testy PROGRAMU.
    - name: Test
      run: dotnet test --no-build --verbosity normal
