//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InferredDataContractsClient.MyNamespace {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CInferredFullName", Namespace="http://schemas.datacontract.org/2004/07/InferredDataContractsService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InferredDataContractsClient.MyNamespace.CInferredFullNameDerived))]
    public partial class CInferredFullName : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CInferredFullNameDerived", Namespace="http://schemas.datacontract.org/2004/07/InferredDataContractsService")]
    [System.SerializableAttribute()]
    public partial class CInferredFullNameDerived : InferredDataContractsClient.MyNamespace.CInferredFullName {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SomeInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SomeInfo {
            get {
                return this.SomeInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.SomeInfoField, value) != true)) {
                    this.SomeInfoField = value;
                    this.RaisePropertyChanged("SomeInfo");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyNamespace.IFullNameService")]
    public interface IFullNameService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFullNameService/GetFullName", ReplyAction="http://tempuri.org/IFullNameService/GetFullNameResponse")]
        InferredDataContractsClient.MyNamespace.CInferredFullName GetFullName(string FirstName, string LastName, int Age);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFullNameService/GetFullNameDerived", ReplyAction="http://tempuri.org/IFullNameService/GetFullNameDerivedResponse")]
        InferredDataContractsClient.MyNamespace.CInferredFullNameDerived GetFullNameDerived(string FirstName, string LastName, int Age, string SomeInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFullNameServiceChannel : InferredDataContractsClient.MyNamespace.IFullNameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FullNameServiceClient : System.ServiceModel.ClientBase<InferredDataContractsClient.MyNamespace.IFullNameService>, InferredDataContractsClient.MyNamespace.IFullNameService {
        
        public FullNameServiceClient() {
        }
        
        public FullNameServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FullNameServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FullNameServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FullNameServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public InferredDataContractsClient.MyNamespace.CInferredFullName GetFullName(string FirstName, string LastName, int Age) {
            return base.Channel.GetFullName(FirstName, LastName, Age);
        }
        
        public InferredDataContractsClient.MyNamespace.CInferredFullNameDerived GetFullNameDerived(string FirstName, string LastName, int Age, string SomeInfo) {
            return base.Channel.GetFullNameDerived(FirstName, LastName, Age, SomeInfo);
        }
    }
}
