// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/ScalarTypes.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace UsingGRPC {

  /// <summary>Holder for reflection information generated from Protos/ScalarTypes.proto</summary>
  public static partial class ScalarTypesReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/ScalarTypes.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ScalarTypesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhQcm90b3MvU2NhbGFyVHlwZXMucHJvdG8SEFVzaW5nR1JQQ1BhY2thZ2Ui",
            "zwIKElNjYWxhclR5cGVzUmVxdWVzdBITCgtGaWVsZERvdWJsZRgBIAEoARIS",
            "CgpGaWVsZEZsb2F0GAIgASgCEhIKCkZpZWxkSW50MzIYAyABKAUSEgoKRmll",
            "bGRJbnQ2NBgEIAEoAxITCgtGaWVsZFVJbnQzMhgFIAEoDRITCgtGaWVsZFVJ",
            "bnQ2NBgGIAEoBBITCgtGaWVsZFNJbnQzMhgHIAEoERITCgtGaWVsZFNJbnQ2",
            "NBgIIAEoEhIUCgxGaWVsZEZpeGVkMzIYCSABKAcSFAoMRmllbGRGaXhlZDY0",
            "GAogASgGEhUKDUZpZWxkU0ZpeGVkMzIYCyABKA8SFQoNRmllbGRTRml4ZWQ2",
            "NBgMIAEoEBIRCglGaWVsZEJvb2wYDSABKAgSEwoLRmllbGRTdHJpbmcYDiAB",
            "KAkSEgoKRmllbGRCeXRlcxgPIAEoDCIuChNTY2FsYXJUeXBlc1Jlc3BvbnNl",
            "EhcKD1Jlc3BvbnNlTWVzc2FnZRgBIAEoCTJwCgtTY2FsYXJUeXBlcxJhChJQ",
            "cm9jZXNzU2NhbGFyVHlwZXMSJC5Vc2luZ0dSUENQYWNrYWdlLlNjYWxhclR5",
            "cGVzUmVxdWVzdBolLlVzaW5nR1JQQ1BhY2thZ2UuU2NhbGFyVHlwZXNSZXNw",
            "b25zZUIMqgIJVXNpbmdHUlBDYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::UsingGRPC.ScalarTypesRequest), global::UsingGRPC.ScalarTypesRequest.Parser, new[]{ "FieldDouble", "FieldFloat", "FieldInt32", "FieldInt64", "FieldUInt32", "FieldUInt64", "FieldSInt32", "FieldSInt64", "FieldFixed32", "FieldFixed64", "FieldSFixed32", "FieldSFixed64", "FieldBool", "FieldString", "FieldBytes" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::UsingGRPC.ScalarTypesResponse), global::UsingGRPC.ScalarTypesResponse.Parser, new[]{ "ResponseMessage" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///--------------------------------------------------------------------------------------------------------------------------------
  ///--------------------------------------------------------------------------------------------------------------------------------
  ///--------------------------------------------------------------------------------------------------------------------------------
  /// </summary>
  public sealed partial class ScalarTypesRequest : pb::IMessage<ScalarTypesRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ScalarTypesRequest> _parser = new pb::MessageParser<ScalarTypesRequest>(() => new ScalarTypesRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ScalarTypesRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UsingGRPC.ScalarTypesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ScalarTypesRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ScalarTypesRequest(ScalarTypesRequest other) : this() {
      fieldDouble_ = other.fieldDouble_;
      fieldFloat_ = other.fieldFloat_;
      fieldInt32_ = other.fieldInt32_;
      fieldInt64_ = other.fieldInt64_;
      fieldUInt32_ = other.fieldUInt32_;
      fieldUInt64_ = other.fieldUInt64_;
      fieldSInt32_ = other.fieldSInt32_;
      fieldSInt64_ = other.fieldSInt64_;
      fieldFixed32_ = other.fieldFixed32_;
      fieldFixed64_ = other.fieldFixed64_;
      fieldSFixed32_ = other.fieldSFixed32_;
      fieldSFixed64_ = other.fieldSFixed64_;
      fieldBool_ = other.fieldBool_;
      fieldString_ = other.fieldString_;
      fieldBytes_ = other.fieldBytes_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ScalarTypesRequest Clone() {
      return new ScalarTypesRequest(this);
    }

    /// <summary>Field number for the "FieldDouble" field.</summary>
    public const int FieldDoubleFieldNumber = 1;
    private double fieldDouble_;
    /// <summary>
    ///--------------------------------------------------------------------------------------------------------------------------------
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double FieldDouble {
      get { return fieldDouble_; }
      set {
        fieldDouble_ = value;
      }
    }

    /// <summary>Field number for the "FieldFloat" field.</summary>
    public const int FieldFloatFieldNumber = 2;
    private float fieldFloat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float FieldFloat {
      get { return fieldFloat_; }
      set {
        fieldFloat_ = value;
      }
    }

    /// <summary>Field number for the "FieldInt32" field.</summary>
    public const int FieldInt32FieldNumber = 3;
    private int fieldInt32_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FieldInt32 {
      get { return fieldInt32_; }
      set {
        fieldInt32_ = value;
      }
    }

    /// <summary>Field number for the "FieldInt64" field.</summary>
    public const int FieldInt64FieldNumber = 4;
    private long fieldInt64_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long FieldInt64 {
      get { return fieldInt64_; }
      set {
        fieldInt64_ = value;
      }
    }

    /// <summary>Field number for the "FieldUInt32" field.</summary>
    public const int FieldUInt32FieldNumber = 5;
    private uint fieldUInt32_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FieldUInt32 {
      get { return fieldUInt32_; }
      set {
        fieldUInt32_ = value;
      }
    }

    /// <summary>Field number for the "FieldUInt64" field.</summary>
    public const int FieldUInt64FieldNumber = 6;
    private ulong fieldUInt64_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong FieldUInt64 {
      get { return fieldUInt64_; }
      set {
        fieldUInt64_ = value;
      }
    }

    /// <summary>Field number for the "FieldSInt32" field.</summary>
    public const int FieldSInt32FieldNumber = 7;
    private int fieldSInt32_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FieldSInt32 {
      get { return fieldSInt32_; }
      set {
        fieldSInt32_ = value;
      }
    }

    /// <summary>Field number for the "FieldSInt64" field.</summary>
    public const int FieldSInt64FieldNumber = 8;
    private long fieldSInt64_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long FieldSInt64 {
      get { return fieldSInt64_; }
      set {
        fieldSInt64_ = value;
      }
    }

    /// <summary>Field number for the "FieldFixed32" field.</summary>
    public const int FieldFixed32FieldNumber = 9;
    private uint fieldFixed32_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FieldFixed32 {
      get { return fieldFixed32_; }
      set {
        fieldFixed32_ = value;
      }
    }

    /// <summary>Field number for the "FieldFixed64" field.</summary>
    public const int FieldFixed64FieldNumber = 10;
    private ulong fieldFixed64_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong FieldFixed64 {
      get { return fieldFixed64_; }
      set {
        fieldFixed64_ = value;
      }
    }

    /// <summary>Field number for the "FieldSFixed32" field.</summary>
    public const int FieldSFixed32FieldNumber = 11;
    private int fieldSFixed32_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FieldSFixed32 {
      get { return fieldSFixed32_; }
      set {
        fieldSFixed32_ = value;
      }
    }

    /// <summary>Field number for the "FieldSFixed64" field.</summary>
    public const int FieldSFixed64FieldNumber = 12;
    private long fieldSFixed64_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long FieldSFixed64 {
      get { return fieldSFixed64_; }
      set {
        fieldSFixed64_ = value;
      }
    }

    /// <summary>Field number for the "FieldBool" field.</summary>
    public const int FieldBoolFieldNumber = 13;
    private bool fieldBool_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool FieldBool {
      get { return fieldBool_; }
      set {
        fieldBool_ = value;
      }
    }

    /// <summary>Field number for the "FieldString" field.</summary>
    public const int FieldStringFieldNumber = 14;
    private string fieldString_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FieldString {
      get { return fieldString_; }
      set {
        fieldString_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "FieldBytes" field.</summary>
    public const int FieldBytesFieldNumber = 15;
    private pb::ByteString fieldBytes_ = pb::ByteString.Empty;
    /// <summary>
    ///--------------------------------------------------------------------------------------------------------------------------------
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString FieldBytes {
      get { return fieldBytes_; }
      set {
        fieldBytes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ScalarTypesRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ScalarTypesRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(FieldDouble, other.FieldDouble)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(FieldFloat, other.FieldFloat)) return false;
      if (FieldInt32 != other.FieldInt32) return false;
      if (FieldInt64 != other.FieldInt64) return false;
      if (FieldUInt32 != other.FieldUInt32) return false;
      if (FieldUInt64 != other.FieldUInt64) return false;
      if (FieldSInt32 != other.FieldSInt32) return false;
      if (FieldSInt64 != other.FieldSInt64) return false;
      if (FieldFixed32 != other.FieldFixed32) return false;
      if (FieldFixed64 != other.FieldFixed64) return false;
      if (FieldSFixed32 != other.FieldSFixed32) return false;
      if (FieldSFixed64 != other.FieldSFixed64) return false;
      if (FieldBool != other.FieldBool) return false;
      if (FieldString != other.FieldString) return false;
      if (FieldBytes != other.FieldBytes) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FieldDouble != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(FieldDouble);
      if (FieldFloat != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(FieldFloat);
      if (FieldInt32 != 0) hash ^= FieldInt32.GetHashCode();
      if (FieldInt64 != 0L) hash ^= FieldInt64.GetHashCode();
      if (FieldUInt32 != 0) hash ^= FieldUInt32.GetHashCode();
      if (FieldUInt64 != 0UL) hash ^= FieldUInt64.GetHashCode();
      if (FieldSInt32 != 0) hash ^= FieldSInt32.GetHashCode();
      if (FieldSInt64 != 0L) hash ^= FieldSInt64.GetHashCode();
      if (FieldFixed32 != 0) hash ^= FieldFixed32.GetHashCode();
      if (FieldFixed64 != 0UL) hash ^= FieldFixed64.GetHashCode();
      if (FieldSFixed32 != 0) hash ^= FieldSFixed32.GetHashCode();
      if (FieldSFixed64 != 0L) hash ^= FieldSFixed64.GetHashCode();
      if (FieldBool != false) hash ^= FieldBool.GetHashCode();
      if (FieldString.Length != 0) hash ^= FieldString.GetHashCode();
      if (FieldBytes.Length != 0) hash ^= FieldBytes.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FieldDouble != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(FieldDouble);
      }
      if (FieldFloat != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(FieldFloat);
      }
      if (FieldInt32 != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(FieldInt32);
      }
      if (FieldInt64 != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(FieldInt64);
      }
      if (FieldUInt32 != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(FieldUInt32);
      }
      if (FieldUInt64 != 0UL) {
        output.WriteRawTag(48);
        output.WriteUInt64(FieldUInt64);
      }
      if (FieldSInt32 != 0) {
        output.WriteRawTag(56);
        output.WriteSInt32(FieldSInt32);
      }
      if (FieldSInt64 != 0L) {
        output.WriteRawTag(64);
        output.WriteSInt64(FieldSInt64);
      }
      if (FieldFixed32 != 0) {
        output.WriteRawTag(77);
        output.WriteFixed32(FieldFixed32);
      }
      if (FieldFixed64 != 0UL) {
        output.WriteRawTag(81);
        output.WriteFixed64(FieldFixed64);
      }
      if (FieldSFixed32 != 0) {
        output.WriteRawTag(93);
        output.WriteSFixed32(FieldSFixed32);
      }
      if (FieldSFixed64 != 0L) {
        output.WriteRawTag(97);
        output.WriteSFixed64(FieldSFixed64);
      }
      if (FieldBool != false) {
        output.WriteRawTag(104);
        output.WriteBool(FieldBool);
      }
      if (FieldString.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(FieldString);
      }
      if (FieldBytes.Length != 0) {
        output.WriteRawTag(122);
        output.WriteBytes(FieldBytes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FieldDouble != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(FieldDouble);
      }
      if (FieldFloat != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(FieldFloat);
      }
      if (FieldInt32 != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(FieldInt32);
      }
      if (FieldInt64 != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(FieldInt64);
      }
      if (FieldUInt32 != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(FieldUInt32);
      }
      if (FieldUInt64 != 0UL) {
        output.WriteRawTag(48);
        output.WriteUInt64(FieldUInt64);
      }
      if (FieldSInt32 != 0) {
        output.WriteRawTag(56);
        output.WriteSInt32(FieldSInt32);
      }
      if (FieldSInt64 != 0L) {
        output.WriteRawTag(64);
        output.WriteSInt64(FieldSInt64);
      }
      if (FieldFixed32 != 0) {
        output.WriteRawTag(77);
        output.WriteFixed32(FieldFixed32);
      }
      if (FieldFixed64 != 0UL) {
        output.WriteRawTag(81);
        output.WriteFixed64(FieldFixed64);
      }
      if (FieldSFixed32 != 0) {
        output.WriteRawTag(93);
        output.WriteSFixed32(FieldSFixed32);
      }
      if (FieldSFixed64 != 0L) {
        output.WriteRawTag(97);
        output.WriteSFixed64(FieldSFixed64);
      }
      if (FieldBool != false) {
        output.WriteRawTag(104);
        output.WriteBool(FieldBool);
      }
      if (FieldString.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(FieldString);
      }
      if (FieldBytes.Length != 0) {
        output.WriteRawTag(122);
        output.WriteBytes(FieldBytes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FieldDouble != 0D) {
        size += 1 + 8;
      }
      if (FieldFloat != 0F) {
        size += 1 + 4;
      }
      if (FieldInt32 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FieldInt32);
      }
      if (FieldInt64 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(FieldInt64);
      }
      if (FieldUInt32 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FieldUInt32);
      }
      if (FieldUInt64 != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(FieldUInt64);
      }
      if (FieldSInt32 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(FieldSInt32);
      }
      if (FieldSInt64 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(FieldSInt64);
      }
      if (FieldFixed32 != 0) {
        size += 1 + 4;
      }
      if (FieldFixed64 != 0UL) {
        size += 1 + 8;
      }
      if (FieldSFixed32 != 0) {
        size += 1 + 4;
      }
      if (FieldSFixed64 != 0L) {
        size += 1 + 8;
      }
      if (FieldBool != false) {
        size += 1 + 1;
      }
      if (FieldString.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FieldString);
      }
      if (FieldBytes.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(FieldBytes);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ScalarTypesRequest other) {
      if (other == null) {
        return;
      }
      if (other.FieldDouble != 0D) {
        FieldDouble = other.FieldDouble;
      }
      if (other.FieldFloat != 0F) {
        FieldFloat = other.FieldFloat;
      }
      if (other.FieldInt32 != 0) {
        FieldInt32 = other.FieldInt32;
      }
      if (other.FieldInt64 != 0L) {
        FieldInt64 = other.FieldInt64;
      }
      if (other.FieldUInt32 != 0) {
        FieldUInt32 = other.FieldUInt32;
      }
      if (other.FieldUInt64 != 0UL) {
        FieldUInt64 = other.FieldUInt64;
      }
      if (other.FieldSInt32 != 0) {
        FieldSInt32 = other.FieldSInt32;
      }
      if (other.FieldSInt64 != 0L) {
        FieldSInt64 = other.FieldSInt64;
      }
      if (other.FieldFixed32 != 0) {
        FieldFixed32 = other.FieldFixed32;
      }
      if (other.FieldFixed64 != 0UL) {
        FieldFixed64 = other.FieldFixed64;
      }
      if (other.FieldSFixed32 != 0) {
        FieldSFixed32 = other.FieldSFixed32;
      }
      if (other.FieldSFixed64 != 0L) {
        FieldSFixed64 = other.FieldSFixed64;
      }
      if (other.FieldBool != false) {
        FieldBool = other.FieldBool;
      }
      if (other.FieldString.Length != 0) {
        FieldString = other.FieldString;
      }
      if (other.FieldBytes.Length != 0) {
        FieldBytes = other.FieldBytes;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            FieldDouble = input.ReadDouble();
            break;
          }
          case 21: {
            FieldFloat = input.ReadFloat();
            break;
          }
          case 24: {
            FieldInt32 = input.ReadInt32();
            break;
          }
          case 32: {
            FieldInt64 = input.ReadInt64();
            break;
          }
          case 40: {
            FieldUInt32 = input.ReadUInt32();
            break;
          }
          case 48: {
            FieldUInt64 = input.ReadUInt64();
            break;
          }
          case 56: {
            FieldSInt32 = input.ReadSInt32();
            break;
          }
          case 64: {
            FieldSInt64 = input.ReadSInt64();
            break;
          }
          case 77: {
            FieldFixed32 = input.ReadFixed32();
            break;
          }
          case 81: {
            FieldFixed64 = input.ReadFixed64();
            break;
          }
          case 93: {
            FieldSFixed32 = input.ReadSFixed32();
            break;
          }
          case 97: {
            FieldSFixed64 = input.ReadSFixed64();
            break;
          }
          case 104: {
            FieldBool = input.ReadBool();
            break;
          }
          case 114: {
            FieldString = input.ReadString();
            break;
          }
          case 122: {
            FieldBytes = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            FieldDouble = input.ReadDouble();
            break;
          }
          case 21: {
            FieldFloat = input.ReadFloat();
            break;
          }
          case 24: {
            FieldInt32 = input.ReadInt32();
            break;
          }
          case 32: {
            FieldInt64 = input.ReadInt64();
            break;
          }
          case 40: {
            FieldUInt32 = input.ReadUInt32();
            break;
          }
          case 48: {
            FieldUInt64 = input.ReadUInt64();
            break;
          }
          case 56: {
            FieldSInt32 = input.ReadSInt32();
            break;
          }
          case 64: {
            FieldSInt64 = input.ReadSInt64();
            break;
          }
          case 77: {
            FieldFixed32 = input.ReadFixed32();
            break;
          }
          case 81: {
            FieldFixed64 = input.ReadFixed64();
            break;
          }
          case 93: {
            FieldSFixed32 = input.ReadSFixed32();
            break;
          }
          case 97: {
            FieldSFixed64 = input.ReadSFixed64();
            break;
          }
          case 104: {
            FieldBool = input.ReadBool();
            break;
          }
          case 114: {
            FieldString = input.ReadString();
            break;
          }
          case 122: {
            FieldBytes = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///--------------------------------------------------------------------------------------------------------------------------------
  ///--------------------------------------------------------------------------------------------------------------------------------
  ///--------------------------------------------------------------------------------------------------------------------------------
  /// </summary>
  public sealed partial class ScalarTypesResponse : pb::IMessage<ScalarTypesResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ScalarTypesResponse> _parser = new pb::MessageParser<ScalarTypesResponse>(() => new ScalarTypesResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ScalarTypesResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UsingGRPC.ScalarTypesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ScalarTypesResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ScalarTypesResponse(ScalarTypesResponse other) : this() {
      responseMessage_ = other.responseMessage_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ScalarTypesResponse Clone() {
      return new ScalarTypesResponse(this);
    }

    /// <summary>Field number for the "ResponseMessage" field.</summary>
    public const int ResponseMessageFieldNumber = 1;
    private string responseMessage_ = "";
    /// <summary>
    ///--------------------------------------------------------------------------------------------------------------------------------
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ResponseMessage {
      get { return responseMessage_; }
      set {
        responseMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ScalarTypesResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ScalarTypesResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResponseMessage != other.ResponseMessage) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ResponseMessage.Length != 0) hash ^= ResponseMessage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ResponseMessage.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ResponseMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ResponseMessage.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ResponseMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ResponseMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ResponseMessage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ScalarTypesResponse other) {
      if (other == null) {
        return;
      }
      if (other.ResponseMessage.Length != 0) {
        ResponseMessage = other.ResponseMessage;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ResponseMessage = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ResponseMessage = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
