// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/ServicesBidirectionalStreaming.proto
// </auto-generated>
// Original file comments:
// --------------------------------------------------------------------------------------------------------------------------------
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace UsingGRPC {
  /// <summary>
  ///--------------------------------------------------------------------------------------------------------------------------------
  ///--------------------------------------------------------------------------------------------------------------------------------
  ///--------------------------------------------------------------------------------------------------------------------------------
  /// </summary>
  public static partial class ServicesBidirectionalStreaming
  {
    static readonly string __ServiceName = "UsingGRPCPackage.ServicesBidirectionalStreaming";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::UsingGRPC.ServicesBidirectionalStreamingRequest> __Marshaller_UsingGRPCPackage_ServicesBidirectionalStreamingRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::UsingGRPC.ServicesBidirectionalStreamingRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::UsingGRPC.ServicesBidirectionalStreamingResponse> __Marshaller_UsingGRPCPackage_ServicesBidirectionalStreamingResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::UsingGRPC.ServicesBidirectionalStreamingResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::UsingGRPC.ServicesBidirectionalStreamingRequest, global::UsingGRPC.ServicesBidirectionalStreamingResponse> __Method_ProcessServicesBidirectionalStreaming = new grpc::Method<global::UsingGRPC.ServicesBidirectionalStreamingRequest, global::UsingGRPC.ServicesBidirectionalStreamingResponse>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "ProcessServicesBidirectionalStreaming",
        __Marshaller_UsingGRPCPackage_ServicesBidirectionalStreamingRequest,
        __Marshaller_UsingGRPCPackage_ServicesBidirectionalStreamingResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::UsingGRPC.ServicesBidirectionalStreamingReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ServicesBidirectionalStreaming</summary>
    [grpc::BindServiceMethod(typeof(ServicesBidirectionalStreaming), "BindService")]
    public abstract partial class ServicesBidirectionalStreamingBase
    {
      /// <summary>
      ///--------------------------------------------------------------------------------------------------------------------------------
      /// !!! METHOD je BIDIRECTIONAL STREAMING METHOD.
      /// </summary>
      /// <param name="requestStream">Used for reading requests from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task ProcessServicesBidirectionalStreaming(grpc::IAsyncStreamReader<global::UsingGRPC.ServicesBidirectionalStreamingRequest> requestStream, grpc::IServerStreamWriter<global::UsingGRPC.ServicesBidirectionalStreamingResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(ServicesBidirectionalStreamingBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ProcessServicesBidirectionalStreaming, serviceImpl.ProcessServicesBidirectionalStreaming).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ServicesBidirectionalStreamingBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_ProcessServicesBidirectionalStreaming, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::UsingGRPC.ServicesBidirectionalStreamingRequest, global::UsingGRPC.ServicesBidirectionalStreamingResponse>(serviceImpl.ProcessServicesBidirectionalStreaming));
    }

  }
}
#endregion
