// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UseTrackingChangesProxies;

#nullable disable

namespace UseTrackingChangesProxies.Migrations
{
    [DbContext(typeof(CDBContext))]
    [Migration("20221201005940_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Proxies:ChangeTracking", true)
                .HasAnnotation("Proxies:CheckEquality", true)
                .HasAnnotation("Proxies:LazyLoading", false);

            modelBuilder.Entity("UseTrackingChangesProxies.CEntityOneToManyTrackingChangesProxiesDependent", b =>
                {
                    b.Property<int>("EntityDependentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntityDependentIntValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityDependentStringValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityPrincipalID")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntityDependentID");

                    b.HasIndex("EntityPrincipalID");

                    b.ToTable("EntitiesOneToManyTrackingChangesProxiesDependent", (string)null);
                });

            modelBuilder.Entity("UseTrackingChangesProxies.CEntityOneToManyTrackingChangesProxiesPrincipal", b =>
                {
                    b.Property<int>("EntityPrincipalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntityPrincipalIntValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityPrincipalStringValue")
                        .HasColumnType("TEXT");

                    b.HasKey("EntityPrincipalID");

                    b.ToTable("EntitiesOneToManyTrackingChangesProxiesPrincipal", (string)null);
                });

            modelBuilder.Entity("UseTrackingChangesProxies.CEntityOneToManyTrackingChangesProxiesDependent", b =>
                {
                    b.HasOne("UseTrackingChangesProxies.CEntityOneToManyTrackingChangesProxiesPrincipal", "EntityPrincipal")
                        .WithMany("EntitiesDependent")
                        .HasForeignKey("EntityPrincipalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityPrincipal");
                });

            modelBuilder.Entity("UseTrackingChangesProxies.CEntityOneToManyTrackingChangesProxiesPrincipal", b =>
                {
                    b.Navigation("EntitiesDependent");
                });
#pragma warning restore 612, 618
        }
    }
}
