//------------------------------------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(FFBC006F-662B-4817-9B72-8DD6943BDAEB),
	// !!! Definuje sa GUID pre ASYNCHRONNY COM INTERFACE.
	async_uuid(1E610375-B6DE-44F3-834D-99D7519E09D8),
    pointer_default(unique),
	// !!!!! Pri COM INTERFACE, ktory je ma byt MARSHALED NESMIE byt nastaveny ATTRIBUTE [local].
]
interface IAsynchronousMethodsTest : IUnknown
{
	HRESULT SetValue([in] BSTR Value);
	HRESULT GetValue([out] BSTR* Value);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
	uuid(3A158138-F9A2-4209-8FCA-F30F47261DEC),
	version(1.0),
]
library AsynchronousMethodsServerLib
{
	importlib("stdole2.tlb");

    [
        uuid(FB76EEC7-C53D-44E6-9390-123922BEEEB2),
    ]
	coclass AsynchronousMethodsObject
	{
		[default] interface IAsynchronousMethodsTest;
	};
};
//------------------------------------------------------------------------------------------------------