//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManualWCFAutoProxyClient.CHelloWorldProxy
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManualWCFAutoProxyClient.CHelloWorldProxy.IHelloWorldContract")]
    public interface IHelloWorldContract
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloWorldContract/SayHelloWorld", ReplyAction="http://tempuri.org/IHelloWorldContract/SayHelloWorldResponse")]
        void SayHelloWorld(string Name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IHelloWorldContractChannel : ManualWCFAutoProxyClient.CHelloWorldProxy.IHelloWorldContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class HelloWorldContractClient : System.ServiceModel.ClientBase<ManualWCFAutoProxyClient.CHelloWorldProxy.IHelloWorldContract>, ManualWCFAutoProxyClient.CHelloWorldProxy.IHelloWorldContract
    {
        
        public HelloWorldContractClient()
        {
        }
        
        public HelloWorldContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public HelloWorldContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public HelloWorldContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public HelloWorldContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void SayHelloWorld(string Name)
        {
            base.Channel.SayHelloWorld(Name);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManualWCFAutoProxyClient.CHelloWorldProxy.IThrowExceptionContract")]
    public interface IThrowExceptionContract
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IThrowExceptionContract/ThrowException", ReplyAction="http://tempuri.org/IThrowExceptionContract/ThrowExceptionResponse")]
        void ThrowException();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IThrowExceptionContractChannel : ManualWCFAutoProxyClient.CHelloWorldProxy.IThrowExceptionContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ThrowExceptionContractClient : System.ServiceModel.ClientBase<ManualWCFAutoProxyClient.CHelloWorldProxy.IThrowExceptionContract>, ManualWCFAutoProxyClient.CHelloWorldProxy.IThrowExceptionContract
    {
        
        public ThrowExceptionContractClient()
        {
        }
        
        public ThrowExceptionContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ThrowExceptionContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ThrowExceptionContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ThrowExceptionContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void ThrowException()
        {
            base.Channel.ThrowException();
        }
    }
}
