//------------------------------------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(F567B9C9-E34B-4ACD-87A1-F4655E2B5BCB),
    pointer_default(unique),
    local
]
interface IGetText1 : IUnknown
{
	// METHOD je ROVNAKO POMENOVANA ako v IGetText2.
	// ALTERNATIVNE sa da pouzit aj [HRESULT GetText([in] int BufferSize, [out,retval,size_is(BufferSize)] wchar_t* Text)].
	HRESULT GetText([in] int BufferSize, [out,string,retval] wchar_t** Text);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(B0722B76-BB23-4216-8468-87CA680AAED3),
    pointer_default(unique),
    local
]
interface IGetText2 : IUnknown
{
	// METHOD je ROVNAKO POMENOVANA ako v IGetText1.
	// ALTERNATIVNE sa da pouzit aj [HRESULT GetText([in] int BufferSize, [out,retval,size_is(BufferSize)] wchar_t* Text)].
	HRESULT GetText([in] int BufferSize, [out,string,retval] wchar_t** Text);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
	uuid(EFFA0431-155B-433E-95B2-F1239DAF5936),
	version(1.0),
]
library MethodsNameClashServerLib
{
	importlib("stdole2.tlb");

    [
        uuid(D30F8E8F-CD97-4255-90BF-0D7EC9B853FA),
    ]
	coclass MethodsNameClashObject
	{
		[default] interface IGetText1;
		interface IGetText2;
	};
};
//------------------------------------------------------------------------------------------------------