//------------------------------------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(93664F4D-CA8C-4F8D-AD0B-5AFF9B210DB1),
    pointer_default(unique),
    local
]
interface ITearOffTextOuter : IUnknown
{
	HRESULT SetTextOuter([in,string] wchar_t* Text);
	// ALTERNATIVNE sa da pouzit aj [HRESULT GetText([in] int BufferSize, [out,retval,size_is(BufferSize)] wchar_t* Text)].
	HRESULT GetTextOuter([in] int BufferSize, [out,string,retval] wchar_t** Text);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(B84E7F7C-9E8B-48BC-85A7-29C387B5241A),
    pointer_default(unique),
    local
]
interface ITearOffTextInner : IUnknown
{
	HRESULT SetTextInner([in,string] wchar_t* Text);
	// ALTERNATIVNE sa da pouzit aj [HRESULT GetText([in] int BufferSize, [out,retval,size_is(BufferSize)] wchar_t* Text)].
	HRESULT GetTextInner([in] int BufferSize, [out,string,retval] wchar_t** Text);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
	uuid(CF07F595-45B7-4F18-8760-E6407179FFA1),
	version(1.0),
]
library TearOffServerLib
{
	importlib("stdole2.tlb");

    [
        uuid(549C91FE-1B9D-4A38-B0C8-A03D50FFD04B),
    ]
	coclass TearOffObject
	{
		[default] interface ITearOffTextOuter;
		interface ITearOffTextInner;
	};
};
//------------------------------------------------------------------------------------------------------