//------------------------------------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(96F3935B-E856-4DBC-89FC-5E0B2D0FB5A8),
    pointer_default(unique),
	dual
]
interface ICustomDispatchTest : IDispatch
{
	[id(1)] HRESULT SetValue(BSTR Value);
	[id(2)] HRESULT GetValue(BSTR* Value);
}
//------------------------------------------------------------------------------------------------------
/*
// !!! Definovanie DISPATCH-ONLY COM INTERFACE.
[
	uuid(96F3935B-E856-4DBC-89FC-5E0B2D0FB5A8),
]
dispinterface ICustomDispatchTest
{
	properties:
	methods:
	[id(1)] HRESULT SetValue(BSTR Value);
	[id(2)] HRESULT GetValue(BSTR* Value);
};
*/
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
	uuid(D4E0C5C2-06BD-49F9-9997-FA3DBEA81840),
	version(1.0),
]
library CustomDispatchServerLib
{
	importlib("stdole2.tlb");

    [
        uuid(9101D33D-B5D7-438F-849B-17908A034969),
    ]
	coclass CustomDispatchObject
	{
		[default] interface ICustomDispatchTest;
	};
};
//------------------------------------------------------------------------------------------------------