//------------------------------------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(DA20BB21-ED75-4C4D-939A-367D7E63F8D3),
    pointer_default(unique),
    local
]
interface ISingletonName : IUnknown
{
	HRESULT SetFirstName([in,string] wchar_t* FirstName);
	HRESULT SetLastName([in,string] wchar_t* LastName);
	HRESULT SetAge([in] int Age);
	// ALTERNATIVNE sa da pouzit aj [HRESULT GetFirstName([in] int BufferSize, [out,retval,size_is(BufferSize)] wchar_t* FirstName)].
	HRESULT GetFirstName([in] int BufferSize, [out,string,retval] wchar_t** FirstName);
	// ALTERNATIVNE sa da pouzit aj [HRESULT GetLastName([in] int BufferSize, [out,retval,size_is(BufferSize)] wchar_t* LastName)].
	HRESULT GetLastName([in] int BufferSize, [out,string,retval] wchar_t** LastName);
	HRESULT GetAge([out,retval] int* Age);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
	uuid(E1D82F33-A203-4FB3-BF5F-C95975C97148),
	version(1.0),
]
library SingletonServerLib
{
	importlib("stdole2.tlb");

    [
        uuid(BC66939B-0747-4085-8F12-42BE0423AB5B),
    ]
	coclass SingletonObject
	{
		[default] interface ISingletonName;
	};
};
//------------------------------------------------------------------------------------------------------