//------------------------------------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(69086C22-221F-4A29-9F91-2D6EB9D1EFFB),
    pointer_default(unique),
	// !!!!! Pri COM INTERFACE, ktory je ma byt MARSHALED NESMIE byt nastaveny ATTRIBUTE [local] a zaroven (uplne NELOGICKY) NESMIE byt definovany v SCOPE 'library', ale MIMO NEHO.
]
interface IMyServerCallback : IUnknown
{
	HRESULT SendMessageToClient([in] BSTR Message);
};
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(DB83FED1-ED27-425C-87B7-FF5036C1F08E),
    pointer_default(unique),
	// !!!!! Pri COM INTERFACE, ktory je ma byt MARSHALED NESMIE byt nastaveny ATTRIBUTE [local] a zaroven (uplne NELOGICKY) NESMIE byt definovany v SCOPE 'library', ale MIMO NEHO.
]
interface IMyServer : IUnknown
{
	HRESULT RegisterCallback([in] IMyServerCallback* Callback);
	HRESULT UnRegisterCallback(void);
	HRESULT SendMessageToServer([in] BSTR Message);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
	uuid(493FFE87-B267-4D96-8CF5-0D786FAA604F),
	version(1.0),
]
library CallbacksInCOMServerLib
{
	importlib("stdole2.tlb");

    [
        uuid(91C07319-AD70-4A12-A070-DC8E76A5BC95),
    ]
	coclass CallbacksInCOMObject
	{
		[default] interface IMyServer;
		interface IMyServerCallback;
	};
};
//------------------------------------------------------------------------------------------------------