//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
namespace InheritanceTwoServices_Client.SimpleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SimpleService.ISimpleTextOperations")]
    public interface ISimpleTextOperations {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleTextOperations/ToUpper", ReplyAction="http://tempuri.org/ISimpleTextOperations/ToUpperResponse")]
        string ToUpper(string Value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISimpleTextOperationsChannel : InheritanceTwoServices_Client.SimpleService.ISimpleTextOperations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimpleTextOperationsClient : System.ServiceModel.ClientBase<InheritanceTwoServices_Client.SimpleService.ISimpleTextOperations>, InheritanceTwoServices_Client.SimpleService.ISimpleTextOperations {
        
        public SimpleTextOperationsClient() {
        }
        
        public SimpleTextOperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimpleTextOperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleTextOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleTextOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ToUpper(string Value) {
            return base.Channel.ToUpper(Value);
        }
    }
}
//-------------------------------------------------------------------------------------------------------