//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace NestedTransactionScopeHost
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class WCFPersistentStoreForWFEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new WCFPersistentStoreForWFEntities object using the connection string found in the 'WCFPersistentStoreForWFEntities' section of the application configuration file.
        /// </summary>
        public WCFPersistentStoreForWFEntities() : base("name=WCFPersistentStoreForWFEntities", "WCFPersistentStoreForWFEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WCFPersistentStoreForWFEntities object.
        /// </summary>
        public WCFPersistentStoreForWFEntities(string connectionString) : base(connectionString, "WCFPersistentStoreForWFEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WCFPersistentStoreForWFEntities object.
        /// </summary>
        public WCFPersistentStoreForWFEntities(EntityConnection connection) : base(connection, "WCFPersistentStoreForWFEntities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CustomTable> CustomTable
        {
            get
            {
                if ((_CustomTable == null))
                {
                    _CustomTable = base.CreateObjectSet<CustomTable>("CustomTable");
                }
                return _CustomTable;
            }
        }
        private ObjectSet<CustomTable> _CustomTable;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CustomTable EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomTable(CustomTable customTable)
        {
            base.AddObject("CustomTable", customTable);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WCFPersistentStoreForWFModel", Name="CustomTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CustomTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CustomTable object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="someData">Initial value of the SomeData property.</param>
        public static CustomTable CreateCustomTable(global::System.Int32 id, global::System.String someData)
        {
            CustomTable customTable = new CustomTable();
            customTable.ID = id;
            customTable.SomeData = someData;
            return customTable;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SomeData
        {
            get
            {
                return _SomeData;
            }
            set
            {
                OnSomeDataChanging(value);
                ReportPropertyChanging("SomeData");
                _SomeData = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SomeData");
                OnSomeDataChanged();
            }
        }
        private global::System.String _SomeData;
        partial void OnSomeDataChanging(global::System.String value);
        partial void OnSomeDataChanged();

        #endregion
    
    }

    #endregion
    
}
