// MyCOM.idl : IDL source for MyCOM
//

// This file will be processed by the MIDL tool to
// produce the type library (MyCOM.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(89155F6A-EBB2-406D-827F-8E482057342F),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IBasicMathClass : IDispatch{
	[id(1)] HRESULT Add([in] LONG A, [in] LONG B, [out] LONG* Result);
};
[
	uuid(BF0BEB18-B1CD-42E1-9A2D-8867BFFB49E8),
	version(1.0),
]
library MyCOMLib
{
	importlib("stdole2.tlb");
	[
		uuid(BEBA7D9F-4DB7-4677-AFBC-73073AACCBA9)		
	]
	coclass BasicMathClass
	{
		[default] interface IBasicMathClass;
	};
};