//------------------------------------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(18D909F7-AEBA-4D61-9A9E-2461BE1CE2A6),
    pointer_default(unique),
	// !!!!! Pri COM INTERFACE, ktory je ma byt MARSHALED NESMIE byt nastaveny ATTRIBUTE [local].
]
interface ICustomMarshalingByValueTest : IUnknown
{
	HRESULT SetValue([in] long Value);
	HRESULT GetValue([out] long* Value);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
	uuid(49E445FA-8496-4669-AB58-BB3AC55827EA),
	version(1.0),
]
library CustomMarshalingByValueServerLib
{
	importlib("stdole2.tlb");

    [
        uuid(1C235F9E-DEC0-4A69-A8A4-AAFE9962B953),
    ]
	coclass CustomMarshalingByValueObject
	{
		[default] interface ICustomMarshalingByValueTest;
	};
};
//------------------------------------------------------------------------------------------------------