//------------------------------------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(466DCC56-1104-4936-AB9B-0A5803FE8786),
    pointer_default(unique),
	// !!!!! Pri COM INTERFACE, ktory je ma byt MARSHALED NESMIE byt nastaveny ATTRIBUTE [local].
	// !!!!! Aj ked je NASTAVENY [oleautomation], tak PS DLL MUSI BYT ZAREGISTROVANA.
	//oleautomation
]
interface IBothThreadingModelTest : IUnknown
{
	HRESULT IncrementValue(void);
	HRESULT GetValue([out] long* Value);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
	uuid(914D8E68-53F7-41CD-B1D7-45E6F507DEAC),
	version(1.0),
]
library BothThreadingModelServerLib
{
	importlib("stdole2.tlb");

    [
        uuid(21C461AC-4829-4D05-BA34-189E5C83FD52),
    ]
	coclass BothThreadingModelObject
	{
		[default] interface IBothThreadingModelTest;
	};
};
//------------------------------------------------------------------------------------------------------