//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
namespace InheritanceOneServiceWithTwoEndpoints_Client.TextService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TextService.ISimpleTextOperations")]
    public interface ISimpleTextOperations {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleTextOperations/ToUpper", ReplyAction="http://tempuri.org/ISimpleTextOperations/ToUpperResponse")]
        string ToUpper(string Value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISimpleTextOperationsChannel : InheritanceOneServiceWithTwoEndpoints_Client.TextService.ISimpleTextOperations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimpleTextOperationsClient : System.ServiceModel.ClientBase<InheritanceOneServiceWithTwoEndpoints_Client.TextService.ISimpleTextOperations>, InheritanceOneServiceWithTwoEndpoints_Client.TextService.ISimpleTextOperations {
        
        public SimpleTextOperationsClient() {
        }
        
        public SimpleTextOperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimpleTextOperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleTextOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleTextOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ToUpper(string Value) {
            return base.Channel.ToUpper(Value);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TextService.IComplexTextContract")]
    public interface IComplexTextContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleTextOperations/ToUpper", ReplyAction="http://tempuri.org/ISimpleTextOperations/ToUpperResponse")]
        string ToUpper(string Value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplexTextContract/ToLower", ReplyAction="http://tempuri.org/IComplexTextContract/ToLowerResponse")]
        string ToLower(string Value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IComplexTextContractChannel : InheritanceOneServiceWithTwoEndpoints_Client.TextService.IComplexTextContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComplexTextContractClient : System.ServiceModel.ClientBase<InheritanceOneServiceWithTwoEndpoints_Client.TextService.IComplexTextContract>, InheritanceOneServiceWithTwoEndpoints_Client.TextService.IComplexTextContract {
        
        public ComplexTextContractClient() {
        }
        
        public ComplexTextContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComplexTextContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComplexTextContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComplexTextContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ToUpper(string Value) {
            return base.Channel.ToUpper(Value);
        }
        
        public string ToLower(string Value) {
            return base.Channel.ToLower(Value);
        }
    }
}
//-------------------------------------------------------------------------------------------------------