//------------------------------------------------------------------------------------------------------
import "oaidl.idl";
import "ocidl.idl";
//------------------------------------------------------------------------------------------------------
[
    object,
	uuid(8F86F1ED-437A-4AD3-9145-C8555480C394),
    pointer_default(unique),
    local
]
interface IComponentCategoriesName : IUnknown
{
	HRESULT SetFirstName([in,string] wchar_t* FirstName);
	HRESULT SetLastName([in,string] wchar_t* LastName);
	HRESULT SetAge([in] int Age);
	// ALTERNATIVNE sa da pouzit aj [HRESULT GetFirstName([in] int BufferSize, [out,retval,size_is(BufferSize)] wchar_t* FirstName)].
	HRESULT GetFirstName([in] int BufferSize, [out,string,retval] wchar_t** FirstName);
	// ALTERNATIVNE sa da pouzit aj [HRESULT GetLastName([in] int BufferSize, [out,retval,size_is(BufferSize)] wchar_t* LastName)].
	HRESULT GetLastName([in] int BufferSize, [out,string,retval] wchar_t** LastName);
	HRESULT GetAge([out,retval] int* Age);
};
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------
[
	uuid(569B8B04-01CE-4662-BC99-877614A41472),
	version(1.0),
]
library ComponentCategoriesServerLib
{
	importlib("stdole2.tlb");

    [
        uuid(7B863799-2690-4EC0-86DD-F4D485FEE332),
    ]
	coclass ComponentCategoriesObject
	{
		[default] interface IComponentCategoriesName;
	};
};
//------------------------------------------------------------------------------------------------------